# Generated by Django 4.2 on 2025-08-18 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('collection_frequency', models.CharField(default='daily', max_length=50)),
                ('total_rooms', models.IntegerField(default=0)),
                ('type', models.CharField(default='hotel', max_length=50)),
                ('waste_per_day', models.IntegerField(default=0)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('payment_account', models.CharField(default='N/A', max_length=100)),
                ('hadhi', models.CharField(default='normal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('Hotel_Manager', 'Hotel_Manager'), ('Admin', 'Admin'), ('Scheduler', 'Scheduler'), ('Driver', 'Driver'), ('Collector', 'Collector')], max_length=20)),
                ('team_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='egaz_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('In_Use', 'In_Use'), ('Maintenance', 'Maintenance')], max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('waste_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard_duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('shift_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('scheduled_start_time', models.DateTimeField()),
                ('scheduled_end_time', models.DateTimeField()),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_teams', to='egaz_app.user')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='egaz_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_estimate', models.CharField(max_length=50)),
                ('urgency_level', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In_Progress', 'In_Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.hotel')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.user')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Pending', max_length=50)),
                ('time', models.TimeField()),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.hotel')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.servicerequest')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['week_start_date', 'day', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_entity_type', models.CharField(choices=[('Request', 'Request'), ('Schedule', 'Schedule'), ('Attendance', 'Attendance')], max_length=20)),
                ('related_entity_id', models.UUIDField()),
                ('message_type', models.CharField(max_length=50)),
                ('message_content', models.TextField()),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Acknowledged', 'Acknowledged')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('On_Time', 'On_Time'), ('Late', 'Late'), ('Early_Departure', 'Early_Departure'), ('Absent', 'Absent')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.workshift')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('Late_Service', 'Late_Service'), ('Worker_Shortage', 'Worker_Shortage'), ('Equipment_Issue', 'Equipment_Issue')], max_length=50)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('triggered_time', models.DateTimeField(auto_now_add=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.user')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egaz_app.schedule')),
            ],
        ),
    ]
