# Generated by Django 5.2.8 on 2025-11-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('sick', 'Sick'), ('accident', 'Accident'), ('off', 'Off')], default='present', max_length=10),
        ),
    ]
