# Generated by Django 5.2.6 on 2025-11-05 22:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('summary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(unique=True)),
                ('total_actual_waste', models.FloatField(default=0.0)),
                ('total_processed_waste', models.FloatField(default=0.0)),
                ('total_actual_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_processed_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Summary',
                'verbose_name_plural': 'Monthly Summaries',
                'ordering': ['-month'],
            },
        ),
        migrations.DeleteModel(
            name='MonthlyHotelSummary',
        ),
    ]
