# Generated by Django 5.2.6 on 2025-11-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('hotel', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='month',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='egaz_app.client'),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_file',
        ),
    ]
