# Generated by Django 4.2 on 2025-08-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0001_initial'),
    ]

    operations = [
    ]
