# Generated by Django 5.2.6 on 2025-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0002_monthlysummary_delete_monthlyhotelsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='processed_payment_report',
            field=models.FileField(blank=True, null=True, upload_to='monthly_reports/payment/'),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='processed_waste_report',
            field=models.FileField(blank=True, null=True, upload_to='monthly_reports/waste/'),
        ),
    ]
