# Generated by Django 5.2.8 on 2025-11-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='files',
            field=models.JSONField(blank=True, default=list, help_text="List of file information: [{'name': 'file1.pdf', 'url': '/media/invoices/file1.pdf'}]"),
        ),
    ]
