# Generated by Django 4.2 on 2025-08-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0002_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='egaz_app.client'),
        ),
        migrations.AddField(
            model_name='pendinghotel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_hotel', to='egaz_app.client'),
        ),
    ]
