# Generated by Django 5.2.6 on 2025-11-12 13:46

import datetime

from django.db import migrations, models


def get_default_client():
    from egaz_app.models import Client
    return Client.objects.first().pk  # primary key of the first client

class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0002_alter_invoice_unique_together_invoice_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(
                default=get_default_client,
                on_delete=models.CASCADE,
                related_name='invoices',
                to='egaz_app.Client',
            ),
        ),
    ]
