# Generated by Django 4.2 on 2025-08-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0002_add_hotel_to_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='egaz_app.hotel'),
        ),
    ]
