# Generated by Django 4.2 on 2025-08-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0003_alter_schedule_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='request',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
