# Generated by Django 5.2.8 on 2025-11-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0003_remove_invoice_amount_remove_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_received',
        ),
    ]
