# Generated by Django 4.2 on 2025-08-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0004_remove_schedule_request_delete_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='assigned_admin',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_time',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='triggered_time',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Late_Service', 'Late_Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical')], max_length=20),
        ),
    ]
