# Generated by Django 4.2 on 2025-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0004_user_date_of_birth_user_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, choices=[('baba', 'Baba'), ('mama', 'Mama'), ('kaka', 'Kaka'), ('dada', 'Dada'), ('babu', 'Babu'), ('bibi', 'Bibi'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
