# Generated by Django 5.2.8 on 2025-11-24 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0004_remove_invoice_is_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('agreement', 'Agreement'), ('license', 'License'), ('certificate', 'Certificate'), ('report', 'Report'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('proposal', 'Proposal'), ('quotation', 'Quotation'), ('policy', 'Policy'), ('manual', 'Manual'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(help_text='Allowed file types: pdf, doc, docx, txt, rtf, xls, xlsx, csv, ppt, pptx, jpg, jpeg, png, gif, zip, rar', upload_to='storage/documents/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storage Document',
                'verbose_name_plural': 'Storage Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'created_at'], name='egaz_app_st_documen_4eab26_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='egaz_app_st_uploade_81a12f_idx')],
            },
        ),
    ]
