# Generated by Django 5.2.8 on 2025-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0005_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='file_type_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='storage',
            index=models.Index(fields=['file_type_category'], name='egaz_app_st_file_ty_f11aed_idx'),
        ),
    ]
