# Generated by Django 5.2.6 on 2025-11-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Supervisors', 'Supervisors'), ('Drivers', 'Drivers'), ('Staff', 'Staff'), ('Workers', 'Workers'), ('Council', 'Council')], default='Workers', max_length=20),
        ),
    ]
