# Generated by Django 4.2 on 2025-09-02 09:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0005_alter_user_emergency_contact_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSalaryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_per_absent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deduction_per_sick_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Supervisors', 'Supervisors'), ('Drivers', 'Drivers'), ('Staff', 'Staff'), ('Workers', 'Workers')], default='Workers', max_length=20),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('month', models.IntegerField(default=9)),
                ('year', models.IntegerField(default=2025)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='egaz_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('sick', 'Sick'), ('accident', 'Accident')], default='present', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='egaz_app.user')),
            ],
        ),
    ]
