# Generated by Django 4.2 on 2025-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0006_rolesalarypolicy_alter_user_role_salary_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspend_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
