# Generated by Django 5.2.8 on 2025-11-27 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0006_storage_file_type_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='egaz_app.client'),
        ),
    ]
