# Generated by Django 5.2.6 on 2025-11-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslip',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='payment_slips/'),
        ),
    ]
