# Generated by Django 4.2 on 2025-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0007_user_delete_comment_user_suspend_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_suspend', 'Pending Suspend'), ('pending_delete', 'Pending Delete'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
