# Generated by Django 5.2.6 on 2025-11-14 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0007_alter_paymentslip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslip',
            name='file',
            field=models.FileField(default=datetime.datetime(2025, 11, 14, 22, 51, 53, 386407, tzinfo=datetime.timezone.utc), upload_to='payment_slips/'),
            preserve_default=False,
        ),
    ]
