# Generated by Django 5.2.8 on 2025-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0007_alter_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='currency',
            field=models.CharField(blank=True, default='TZS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='total_rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='waste_per_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pendinghotel',
            name='hadhi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendinghotel',
            name='payment_account',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendinghotel',
            name='total_rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pendinghotel',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
