# Generated by Django 5.2.6 on 2025-11-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0008_alter_paymentslip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='total_actual_payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='total_processed_payment',
            field=models.FloatField(default=0.0),
        ),
    ]
