# Generated by Django 5.2.8 on 2025-12-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0008_alter_hotel_currency_alter_hotel_total_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='waste_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='month',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=12),
        ),
    ]
