# Generated by Django 4.2 on 2025-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0008_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
