# Generated by Django 4.2 on 2025-09-03 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0009_delete_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='bonuses',
        ),
        migrations.AddField(
            model_name='rolesalarypolicy',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
    model_name='salary',
    name='policy',
    field=models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE,
        related_name='salaries',
        to='egaz_app.rolesalarypolicy',
        null=True,
        blank=True,
    ),
),

    ]
