# Generated by Django 5.2.6 on 2025-11-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0009_alter_monthlysummary_total_actual_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Auto-generated invoice number (FI-INV-YYYY-MM-NNNN)', max_length=20, null=True),
        ),
    ]
