# Generated by Django 5.2.8 on 2025-12-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0009_alter_hotel_waste_per_day_alter_invoice_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
