# Generated by Django 5.2.6 on 2025-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0010_alter_invoice_options_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Auto-generated invoice number (FI-INV-YYYY-MM-NNNN)', max_length=20, null=True, unique=True),
        ),
    ]
