# Generated by Django 5.2.6 on 2025-12-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0010_alter_user_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('06:00 – 12:00', 'Morning (06:00 – 12:00)'), ('12:00 – 18:00', 'Afternoon (12:00 – 18:00)')], default='Morning', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('hotel', 'day', 'slot', 'week_start_date')},
        ),
    ]
