# Generated by Django 4.2 on 2025-09-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0010_remove_salary_bonuses_rolesalarypolicy_bonuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='egaz_app.rolesalarypolicy'),
        ),
    ]
