# Generated by Django 5.2.6 on 2025-12-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0011_schedule_schedule_date_alter_schedule_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('06:00 – 12:00', 'Morning (06:00 – 12:00)'), ('06:00 – 18:00', 'Afternoon (06:00 – 18:00)')], default='Morning', max_length=20),
        ),
    ]
