# Generated by Django 4.2 on 2025-09-06 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0013_attendance_comment_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidHotelInfo',
            fields=[
                ('paid_hotel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('hadhi', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('payment_account', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_info', to='egaz_app.hotel')),
            ],
        ),
    ]
