# Generated by Django 4.2 on 2025-09-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0014_paidhotelinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['week_start_date', 'day', 'slot'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('Morning', 'Morning (04:00 – 12:00)'), ('Afternoon', 'Afternoon (13:00 – 15:00)')], default='Morning', max_length=20),
        ),
    ]
