# Generated by Django 4.2 on 2025-09-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0015_alter_schedule_options_remove_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('04:00 – 12:00', 'Morning (04:00 – 12:00)'), ('12:30 – 15:00', 'Afternoon (12:30 – 15:00)')], default='Morning', max_length=20),
        ),
    ]
