# Generated by Django 4.2 on 2025-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0016_alter_schedule_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
