# Generated by Django 4.2 on 2025-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0017_user_receive_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
