# Generated by Django 4.2 on 2025-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0018_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finaldelete_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
