# Generated by Django 4.2 on 2025-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0020_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('sick', 'Sick'), ('accident', 'Accident'), ('off', 'Off')], max_length=10),
        ),
    ]
