# Generated by Django 4.2 on 2025-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0021_attendance_absent_count_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Check if this schedule should be visible to users'),
        ),
    ]
