# Generated by Django 4.2 on 2025-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0022_schedule_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Check if this schedule should be visible to users'),
        ),
    ]
