# Generated by Django 4.2 on 2025-09-16 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egaz_app', '0023_alter_schedule_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_time'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='expiry_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_entity_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_entity_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='client_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_client_notifications', to='egaz_app.client'),
        ),
        migrations.AddField(
            model_name='notification',
            name='client_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_client_notifications', to='egaz_app.client'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_content',
            field=models.TextField(help_text='Content of the notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Acknowledged', 'Acknowledged')], default='Unread', max_length=20),
        ),
    ]
