# Generated by Django 4.2 on 2025-09-16 10:53
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('egaz_app', '0024_alter_notification_options_and_more'),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name='notification',
            name='client_recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='client_sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),

        # Add new generic relation fields — NO DEFAULTS, allow null for safety
        migrations.AddField(
            model_name='notification',
            name='sender_content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_notifications',
                to='contenttypes.ContentType',
                null=True  # Will be filled later
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_object_id',
            field=models.UUIDField(
                null=True  # To store client_id or user_id
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='received_notifications',
                to='contenttypes.ContentType',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_object_id',
            field=models.UUIDField(
                null=True
            ),
        ),
    ]