# Generated by Django 4.2 on 2025-09-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('egaz_app', '0025_remove_notification_client_recipient_and_more'),
    ]

    operations = [
        # Keep ordering
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_time']},
        ),
        # Ensure message_content is TextField
        migrations.AlterField(
            model_name='notification',
            name='message_content',
            field=models.TextField(),
        ),
        # Make recipient optional for broadcasts
        migrations.AlterField(
            model_name='notification',
            name='recipient_content_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='received_notifications',
                to='contenttypes.contenttype'
            ),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_object_id',
            field=models.UUIDField(
                blank=True,
                null=True
            ),
        ),
        # Make sender_content_type required but remove wrong datetime default
        migrations.AlterField(
            model_name='notification',
            name='sender_content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_notifications',
                to='contenttypes.contenttype'
            ),
        ),
        # Ensure sender_object_id remains UUIDField
        migrations.AlterField(
            model_name='notification',
            name='sender_object_id',
            field=models.UUIDField(),
        ),
    ]
