# Generated by Django 4.2 on 2025-09-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0026_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('06:00 – 12:00', 'Morning (06:00 – 12:00)'), ('06:00 – 18:00', 'Afternoon (00:30 – 18:00)')], default='Morning', max_length=20),
        ),
    ]
