# Generated by Django 4.2 on 2025-09-23 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0027_alter_schedule_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('slip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='payment_slips/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('month_paid', models.DateField()),
                ('status', models.CharField(choices=[('current', 'Current Month'), ('previous', 'Previous Month')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_slips', to='egaz_app.client')),
            ],
        ),
    ]
