# Generated by Django 4.2 on 2025-09-25 23:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0028_paymentslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidhotelinfo',
            name='month',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 23, 51, 9, 20440, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paidhotelinfo',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_info', to='egaz_app.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='paidhotelinfo',
            unique_together={('hotel', 'month')},
        ),
    ]
