# Generated by Django 5.2.6 on 2025-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0029_paidhotelinfo_month_alter_paidhotelinfo_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=10),
        ),
    ]
