# Generated by Django 5.2.6 on 2025-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0030_alter_salary_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
