# Generated by Django 5.2.6 on 2025-10-03 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0031_paymentslip_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHotelSummary',
            fields=[
                ('summary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('total_waste_litres', models.FloatField(default=0.0)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='egaz_app.client')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('client', 'month')},
            },
        ),
    ]
