# Generated by Django 5.2.6 on 2025-10-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egaz_app', '0033_failedloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
