from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
from egaz_app.models import MonthlySummary

def generate_payment_pdf(month):
    """
    Generate a beautifully formatted PDF report for processed payments for a specific month.
    """
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # ========== HEADER SECTION ==========
    p.setFont("Helvetica-Bold", 16)
    p.setFillColor(colors.HexColor("#003366"))  # Dark Blue
    p.drawCentredString(width / 2, height - 50, "FORSTER INVESTMENT LTD")

    p.setFont("Helvetica", 10)
    p.drawCentredString(width / 2, height - 65, "P.O.BOX 1345, HOUSE KS KM 162 AIRPORT ROAD, ZANZIBAR – TANZANIA")
    p.drawCentredString(width / 2, height - 80, "Email: info@fosterinvestment.co.uk | Tel: +255 716920506 +255 657 832 327")

    # Line separator
    p.setStrokeColor(colors.black)
    p.line(40, height - 90, width - 40, height - 90)

    # ========== TITLE SECTION ==========
    p.setFont("Helvetica-Bold", 16)
    p.setFillColor(colors.HexColor("#003366"))  # Dark Blue for title
    p.drawCentredString(width / 2, height - 120, "MONTHLY PAYMENT REPORT")

    p.setFont("Helvetica", 12)
    p.setFillColor(colors.HexColor("#003366"))  # Dark Blue for subtitle
    month_str = month.strftime("%B %Y")
    p.drawCentredString(width / 2, height - 140, f"For the Month of {month_str}")

    p.setFillColor(colors.black)  # reset color to black for rest of content

    # Recipient
    p.setFont("Helvetica", 11)
    p.drawString(50, height - 170, "To:")
    p.setFont("Helvetica-Bold", 11)
    p.drawString(70, height - 170, "BARAZA LA MJI MKOA WA KUSINI UNGUJA")  # Uppercase

    p.setFont("Helvetica", 11)
    p.drawString(50, height - 190, "From: FORSTER INVESTMENT LTD")

    # ========== FETCH DATA ==========
    try:
        summary = MonthlySummary.objects.get(month=month)
        processed_payment = summary.total_processed_payment
    except MonthlySummary.DoesNotExist:
        processed_payment = 0

    # ========== MAIN TEXT ==========
    p.setFont("Helvetica", 12)
    p.drawString(50, height - 230, "Subject:  Payment Summary")

    p.setFont("Helvetica", 11)
    p.drawString(50, height - 260, "We hereby submit the total payments for the mentioned period:")

    # ========== TABLE SECTION ==========
    table_data = [
        ["Month", "Payment (TZS)"],
        [month_str, f"{processed_payment:,.2f}"],
    ]

    table = Table(table_data, colWidths=[250, 200])
    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#003366")),  # header background
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ])
    table.setStyle(style)
    table.wrapOn(p, width, height)
    table.drawOn(p, 80, height - 370)

    # ========== FOOTER TEXT ==========
    p.setFont("Helvetica", 11)
    p.setFillColor(colors.black)
    p.drawString(50, height - 420, "All transactions have been reviewed and verified accordingly.")
    p.drawString(50, height - 440, "This report is generated automatically by the Forster Investment Ltd system.")

    # Signature Section
    p.setFont("Helvetica-Bold", 11)
    p.drawString(50, height - 480, "Authorized Signature:")
    p.line(180, height - 483, 380, height - 483)
    p.setFont("Helvetica", 10)
    p.drawString(50, height - 500, "Forster Investment Ltd Representative")

    # ========== FOOTER ==========
    p.setStrokeColor(colors.grey)
    p.line(40, 80, width - 40, 80)
    p.setFont("Helvetica", 9)
    p.setFillColor(colors.grey)
    p.drawCentredString(width / 2, 65, "Generated by Forster Investment Ltd Waste Management System")
    p.drawCentredString(width / 2, 50, "© 2025 Forster Investment Ltd - All Rights Reserved")

    # Save PDF
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer
